
CREATE OR REPLACE FUNCTION ${CURRENT_SCHEMA}.UDFBUILDISO8601DATE(year INT, month INT, day INT)
RETURNS TIMESTAMP_NTZ
LANGUAGE SQL
AS
$$
  CASE 
    WHEN year IS NULL OR month IS NULL OR day IS NULL THEN NULL
    WHEN month < 1 OR month > 12 THEN NULL
    WHEN day < 1 OR day > 31 THEN NULL
    ELSE TIMESTAMP_NTZ_FROM_PARTS(year, month, day, 0, 0, 0)
  END
$$;