USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_PROD_RO;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_PROD_RW;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_DEV_RO;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_DEV_RW;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_QA_RO;
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS RETAIL_QA_RW;
USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS RCHETHAN
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_WAREHOUSE = RETAIL_ADHOC_WH
    PASSWORD = 'Temp#1234@'
    MUST_CHANGE_PASSWORD = true;
USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS SPSHIVA
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_WAREHOUSE = RETAIL_ADHOC_WH
    PASSWORD = 'Temp#1234@'
    MUST_CHANGE_PASSWORD = true;
USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS SRAMANUJAN
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_WAREHOUSE = RETAIL_ADHOC_WH
    PASSWORD = 'Temp#1234@'
    MUST_CHANGE_PASSWORD = true;
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS LOAD_MONITOR
    CREDIT_QUOTA = 20
    FREQUENCY = DAILY
    NOTIFY_USERS = null;
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS RETAIL_ADHOC_WH
    INITIALLY_SUSPENDED = true
    WAREHOUSE_TYPE = 'STANDARD';
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RETAIL_PROD;
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RETAIL_DEV;
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS RETAIL_QA;
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE RETAIL_PROD TO ROLE RETAIL_PROD_RO;
USE ROLE SECURITYADMIN;
GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE, APPLYBUDGET ON DATABASE RETAIL_PROD TO ROLE RETAIL_PROD_RW;
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE RETAIL_DEV TO ROLE RETAIL_DEV_RO;
USE ROLE SECURITYADMIN;
GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE, APPLYBUDGET ON DATABASE RETAIL_DEV TO ROLE RETAIL_DEV_RW;
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE RETAIL_QA TO ROLE RETAIL_QA_RO;
USE ROLE SECURITYADMIN;
GRANT CREATE SCHEMA, MODIFY, MONITOR, USAGE, APPLYBUDGET ON DATABASE RETAIL_QA TO ROLE RETAIL_QA_RW;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_PROD_RO TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_PROD_RW TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_DEV_RO TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_DEV_RW TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_QA_RO TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_QA_RW TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER RCHETHAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_PROD_RO TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_PROD_RW TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_DEV_RO TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_DEV_RW TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_QA_RO TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_QA_RW TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER SPSHIVA;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_PROD_RO TO USER SRAMANUJAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_PROD_RW TO USER SRAMANUJAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_DEV_RO TO USER SRAMANUJAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_DEV_RW TO USER SRAMANUJAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_QA_RO TO USER SRAMANUJAN;
USE ROLE SECURITYADMIN;
GRANT ROLE RETAIL_QA_RW TO USER SRAMANUJAN;
USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER SRAMANUJAN;
USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS RETAIL_PROD.MIGRATE;
USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS RETAIL_DEV.MIGRATE;
USE ROLE SYSADMIN;
CREATE SCHEMA IF NOT EXISTS RETAIL_QA.MIGRATE;
